Repository prgrms-web-devcourse-final-project/WEB1_2_Child-Learn_BE, pull requests merged in 2024-11, with the labels that each got.

#23 [Test] PR TEST
  src/main/java/com/prgrms/ijuju/test/Test.java
  src/main/java/com/prgrms/ijuju/test/TestPR.java
Labels: ✅ Test

#25 [Feat] Stock 기능 개발
  src/main/java/com/prgrms/ijuju/IjujuApplication.java
  src/main/java/com/prgrms/ijuju/stock/adv/advancedinvest/dto/request/AdvancedRequestDTO.java
  src/main/java/com/prgrms/ijuju/stock/adv/advancedinvest/dto/response/AdvancedResponseDTO.java
  src/main/java/com/prgrms/ijuju/stock/adv/advancedinvest/entity/AdvancedInvest.java
  src/main/java/com/prgrms/ijuju/stock/adv/advstock/constant/DataType.java
  src/main/java/com/prgrms/ijuju/stock/adv/advstock/controller/AdvStockController.java
  src/main/java/com/prgrms/ijuju/stock/adv/advstock/dto/PolygonCandleResponse.java
  src/main/java/com/prgrms/ijuju/stock/adv/advstock/dto/PolygonCandleResult.java
  src/main/java/com/prgrms/ijuju/stock/adv/advstock/entity/AdvStock.java
  src/main/java/com/prgrms/ijuju/stock/adv/advstock/repository/AdvStockRepository.java
  src/main/java/com/prgrms/ijuju/stock/adv/advstock/scheduler/AdvStockScheduler.java
  src/main/java/com/prgrms/ijuju/stock/adv/advstock/service/AdvStockDataFetcher.java
  src/main/java/com/prgrms/ijuju/stock/adv/advstock/service/AdvStockService.java
  src/main/java/com/prgrms/ijuju/stock/adv/advstock/service/AdvStockServiceImpl.java
  src/main/java/com/prgrms/ijuju/stock/adv/advstock/util/DateUtil.java
  src/main/java/com/prgrms/ijuju/stock/advanced/entity/AdvancedStock.java
Labels: ✨ Feature

#30 [Fix] develop 충돌 해결
  .gitignore
  build.gradle
  ijuju_dev.mv.db
  ijuju_dev.trace.db
  src/main/java/com/prgrms/ijuju/IjujuApplication.java
  src/main/java/com/prgrms/ijuju/common/BaseTimeEntity.java
  src/main/java/com/prgrms/ijuju/common/util/ApiResponse.java
  src/main/java/com/prgrms/ijuju/domain/stock/mid/config/InitMidDb.java
  src/main/java/com/prgrms/ijuju/domain/stock/mid/controller/MidStockController.java
  src/main/java/com/prgrms/ijuju/domain/stock/mid/dto/request/MidStockBuyRequest.java
  src/main/java/com/prgrms/ijuju/domain/stock/mid/dto/request/MidStockSellRequest.java
  src/main/java/com/prgrms/ijuju/domain/stock/mid/dto/response/MidStockPriceResponse.java
  src/main/java/com/prgrms/ijuju/domain/stock/mid/dto/response/MidStockResponse.java
  src/main/java/com/prgrms/ijuju/domain/stock/mid/dto/response/MidStockTradeInfo.java
  src/main/java/com/prgrms/ijuju/domain/stock/mid/dto/response/MidStockWithTradesResponse.java
  src/main/java/com/prgrms/ijuju/domain/stock/mid/dto/response/TradeAvailableResponse.java
  src/main/java/com/prgrms/ijuju/domain/stock/mid/entity/MidStock.java
  src/main/java/com/prgrms/ijuju/domain/stock/mid/entity/MidStockPrice.java
  src/main/java/com/prgrms/ijuju/domain/stock/mid/entity/MidStockTrade.java
  src/main/java/com/prgrms/ijuju/domain/stock/mid/entity/TradeType.java
  src/main/java/com/prgrms/ijuju/domain/stock/mid/repository/MidStockPriceRepository.java
  src/main/java/com/prgrms/ijuju/domain/stock/mid/repository/MidStockPriceRepositoryCustom.java
  src/main/java/com/prgrms/ijuju/domain/stock/mid/repository/MidStockPriceRepositoryImpl.java
  src/main/java/com/prgrms/ijuju/domain/stock/mid/repository/MidStockRepository.java
  src/main/java/com/prgrms/ijuju/domain/stock/mid/repository/MidStockTradeRepository.java
  src/main/java/com/prgrms/ijuju/domain/stock/mid/scheduler/StockPriceScheduler.java
  src/main/java/com/prgrms/ijuju/domain/stock/mid/service/MidStockChartService.java
  src/main/java/com/prgrms/ijuju/domain/stock/mid/service/MidStockService.java
  src/main/java/com/prgrms/ijuju/domain/stock/mid/service/MidStockTradeService.java
  src/main/resources/application-dev.yml
  src/test/java/com/prgrms/ijuju/domain/stock/mid/repository/MidStockPriceRepositoryTest.java
  src/test/java/com/prgrms/ijuju/domain/stock/mid/service/MidStockServiceTest.java
Labels: 🐞 BugFix

#35 Point 기능 구현
  src/main/java/com/prgrms/ijuju/domain/point/controller/PointController.java
  src/main/java/com/prgrms/ijuju/domain/point/dto/request/ExchangeRequestDTO.java
  src/main/java/com/prgrms/ijuju/domain/point/dto/request/PointFilterRequestDTO.java
  src/main/java/com/prgrms/ijuju/domain/point/dto/request/PointRequestDTO.java
  src/main/java/com/prgrms/ijuju/domain/point/dto/response/ExchangeDetailsResponseDTO.java
  src/main/java/com/prgrms/ijuju/domain/point/dto/response/PointDetailsResponseDTO.java
  src/main/java/com/prgrms/ijuju/domain/point/dto/response/PointResponseDTO.java
  src/main/java/com/prgrms/ijuju/domain/point/entity/ExchangeDetails.java
  src/main/java/com/prgrms/ijuju/domain/point/entity/GamePoint.java
  src/main/java/com/prgrms/ijuju/domain/point/entity/GameType.java
  src/main/java/com/prgrms/ijuju/domain/point/entity/PointDetails.java
  src/main/java/com/prgrms/ijuju/domain/point/entity/PointStatus.java
  src/main/java/com/prgrms/ijuju/domain/point/entity/PointType.java
  src/main/java/com/prgrms/ijuju/domain/point/entity/StockPoint.java
  src/main/java/com/prgrms/ijuju/domain/point/entity/StockStatus.java
  src/main/java/com/prgrms/ijuju/domain/point/entity/StockType.java
  src/main/java/com/prgrms/ijuju/domain/point/repository/ExchangeRepository.java
  src/main/java/com/prgrms/ijuju/domain/point/repository/GamePointRepository.java
  src/main/java/com/prgrms/ijuju/domain/point/repository/PointDetailsRepository.java
  src/main/java/com/prgrms/ijuju/domain/point/repository/StockPointRepository.java
  src/main/java/com/prgrms/ijuju/domain/point/service/PointService.java
  src/test/java/com/prgrms/ijuju/domain/point/controller/PointControllerTest.java
  src/test/java/com/prgrms/ijuju/domain/point/service/PointServiceTest.java
Labels: ✨ Feature

#37 [Feat] 모의투자 중급 구현
  src/main/java/com/prgrms/ijuju/domain/stock/mid/controller/MidStockController.java
  src/main/java/com/prgrms/ijuju/domain/stock/mid/dto/request/MidStockBuyRequest.java
  src/main/java/com/prgrms/ijuju/domain/stock/mid/dto/request/MidStockSellRequest.java
  src/main/java/com/prgrms/ijuju/domain/stock/mid/dto/request/MidStockTradePointRequest.java
  src/main/java/com/prgrms/ijuju/domain/stock/mid/dto/response/MidStockPriceResponse.java
  src/main/java/com/prgrms/ijuju/domain/stock/mid/entity/MidStockTrade.java
  src/main/java/com/prgrms/ijuju/domain/stock/mid/exception/MidAlreadyBoughtException.java
  src/main/java/com/prgrms/ijuju/domain/stock/mid/exception/MidAlreadySoldException.java
  src/main/java/com/prgrms/ijuju/domain/stock/mid/exception/MidMemberNotFoundException.java
  src/main/java/com/prgrms/ijuju/domain/stock/mid/exception/MidPointsNotEnoughException.java
  src/main/java/com/prgrms/ijuju/domain/stock/mid/exception/MidPriceNotFoundException.java
  src/main/java/com/prgrms/ijuju/domain/stock/mid/exception/MidStockErrorCode.java
  src/main/java/com/prgrms/ijuju/domain/stock/mid/exception/MidStockException.java
  src/main/java/com/prgrms/ijuju/domain/stock/mid/exception/MidStockNotFoundException.java
  src/main/java/com/prgrms/ijuju/domain/stock/mid/repository/MidStockPriceRepository.java
  src/main/java/com/prgrms/ijuju/domain/stock/mid/repository/MidStockPriceRepositoryImpl.java
  src/main/java/com/prgrms/ijuju/domain/stock/mid/repository/MidStockTradeRepository.java
  src/main/java/com/prgrms/ijuju/domain/stock/mid/service/MidStockChartService.java
  src/main/java/com/prgrms/ijuju/domain/stock/mid/service/MidStockService.java
  src/main/java/com/prgrms/ijuju/domain/stock/mid/service/MidStockTradeService.java
  src/main/resources/test-data.sql
  src/test/java/com/prgrms/ijuju/domain/point/controller/PointControllerTest.java
  src/test/java/com/prgrms/ijuju/domain/point/service/PointServiceTest.java
  src/test/java/com/prgrms/ijuju/domain/stock/mid/service/MidStockServiceTest.java
Labels: ✨ Feature

#45 [Feat] 초급 모의 투자 구현
  src/main/java/com/prgrms/ijuju/domain/member/entity/Member.java
  src/main/java/com/prgrms/ijuju/domain/member/service/MemberService.java
  src/main/java/com/prgrms/ijuju/domain/stock/begin/config/ChatGptConfig.java
  src/main/java/com/prgrms/ijuju/domain/stock/begin/controller/BeginStockController.java
  src/main/java/com/prgrms/ijuju/domain/stock/begin/dto/request/BeginChatGptMessage.java
  src/main/java/com/prgrms/ijuju/domain/stock/begin/dto/request/ChatGptRequest.java
  src/main/java/com/prgrms/ijuju/domain/stock/begin/dto/response/BeginStockPriceResponse.java
  src/main/java/com/prgrms/ijuju/domain/stock/begin/dto/response/BeginStockQuizResponse.java
  src/main/java/com/prgrms/ijuju/domain/stock/begin/dto/response/BeginStockResponse.java
  src/main/java/com/prgrms/ijuju/domain/stock/begin/dto/response/ChatGptResponse.java
  src/main/java/com/prgrms/ijuju/domain/stock/begin/entity/BeginQuiz.java
  src/main/java/com/prgrms/ijuju/domain/stock/begin/entity/BeginStockPrice.java
  src/main/java/com/prgrms/ijuju/domain/stock/begin/entity/LimitBeginStock.java
  src/main/java/com/prgrms/ijuju/domain/stock/begin/exception/BeginStockErrorCode.java
  src/main/java/com/prgrms/ijuju/domain/stock/begin/exception/BeginStockException.java
  src/main/java/com/prgrms/ijuju/domain/stock/begin/init/InitBeginStockPriceData.java
  src/main/java/com/prgrms/ijuju/domain/stock/begin/repository/BeginQuizRepository.java
  src/main/java/com/prgrms/ijuju/domain/stock/begin/repository/BeginStockPriceRepository.java
  src/main/java/com/prgrms/ijuju/domain/stock/begin/repository/LimitBeginStockRepository.java
  src/main/java/com/prgrms/ijuju/domain/stock/begin/scheduler/BeginStockScheduler.java
  src/main/java/com/prgrms/ijuju/domain/stock/begin/service/BeginStockGptService.java
  src/main/java/com/prgrms/ijuju/domain/stock/begin/service/BeginStockPriceService.java
  src/main/java/com/prgrms/ijuju/domain/stock/begin/service/BeginStockService.java
  src/main/resources/application.yml
  src/test/java/com/prgrms/ijuju/domain/stock/begin/repository/BeginStockPriceRepositoryTest.java
  src/test/java/com/prgrms/ijuju/domain/stock/begin/repository/LimitBeginStockRepositoryTest.java
Labels: ✨ Feature

#52 [Feat] 카드뒤집기 기능 구현
  src/main/java/com/prgrms/ijuju/domain/minigame/flipcard/config/FlipCardDataInitializer.java
  src/main/java/com/prgrms/ijuju/domain/minigame/flipcard/controller/FlipCardController.java
  src/main/java/com/prgrms/ijuju/domain/minigame/flipcard/dto/request/FlipCardDto.java
  src/main/java/com/prgrms/ijuju/domain/minigame/flipcard/dto/response/FlipCardResponse.java
  src/main/java/com/prgrms/ijuju/domain/minigame/flipcard/dto/response/PlayFlipCardAvailable.java
  src/main/java/com/prgrms/ijuju/domain/minigame/flipcard/entity/FlipCard.java
  src/main/java/com/prgrms/ijuju/domain/minigame/flipcard/entity/LimitCardGame.java
  src/main/java/com/prgrms/ijuju/domain/minigame/flipcard/exception/FlipCardDfficultyNotFoundException.java
  src/main/java/com/prgrms/ijuju/domain/minigame/flipcard/exception/FlipCardErrorCode.java
  src/main/java/com/prgrms/ijuju/domain/minigame/flipcard/exception/FlipCardException.java
  src/main/java/com/prgrms/ijuju/domain/minigame/flipcard/exception/FlipCardMemberNotFoundException.java
  src/main/java/com/prgrms/ijuju/domain/minigame/flipcard/repository/FlipCardRepository.java
  src/main/java/com/prgrms/ijuju/domain/minigame/flipcard/repository/LimitCardGameRepository.java
  src/main/java/com/prgrms/ijuju/domain/minigame/flipcard/service/FlipCardService.java
  src/main/java/com/prgrms/ijuju/domain/stock/mid/config/InitMidDb.java
  src/main/java/com/prgrms/ijuju/domain/stock/mid/repository/MidStockPriceRepository.java
  src/main/java/com/prgrms/ijuju/domain/stock/mid/repository/MidStockPriceRepositoryCustom.java
  src/main/java/com/prgrms/ijuju/domain/stock/mid/repository/MidStockPriceRepositoryImpl.java
  src/main/java/com/prgrms/ijuju/domain/stock/mid/repository/MidStockTradeRepository.java
  src/main/java/com/prgrms/ijuju/domain/stock/mid/service/MidStockChartService.java
  src/main/java/com/prgrms/ijuju/domain/stock/mid/service/MidStockTradeService.java
  src/main/resources/minigame-data/flip-card.json
  src/main/resources/minigame-data/korean-words-game.json
  src/main/resources/test-data.sql
  src/test/java/com/prgrms/ijuju/domain/minigame/flipcard/controller/FlipCardControllerTest.java
  src/test/java/com/prgrms/ijuju/domain/minigame/flipcard/service/FlipCardServiceTest.java
Labels: ✨ Feature

#56 [Feat] 낱말퀴즈 단어 추가
  src/main/java/com/prgrms/ijuju/domain/minigame/flipcard/config/FlipCardDataInitializer.java
  src/main/java/com/prgrms/ijuju/domain/minigame/flipcard/exception/FlipCardInitializationException.java
  src/main/java/com/prgrms/ijuju/domain/minigame/wordquiz/config/WordQuizDataInitializer.java
  src/main/java/com/prgrms/ijuju/domain/minigame/wordquiz/dto/request/WordQuizDbDto.java
  src/main/java/com/prgrms/ijuju/domain/minigame/wordquiz/entity/WordQuiz.java
  src/main/java/com/prgrms/ijuju/domain/minigame/wordquiz/exception/WordQuizInitializationException.java
  src/main/java/com/prgrms/ijuju/domain/minigame/wordquiz/repository/WordQuizRepository.java
  src/main/java/com/prgrms/ijuju/global/config/ObjectMapperConfig.java
Labels: ✨ Feature, 🔧 Refactor

#55 [Feat] 고급 모의투자 게임 구현
  build.gradle
  src/main/java/com/prgrms/ijuju/common/util/WebSocketUtil.java
  src/main/java/com/prgrms/ijuju/domain/stock/adv/advancedinvest/constant/GameStage.java
  src/main/java/com/prgrms/ijuju/domain/stock/adv/advancedinvest/controller/AdvancedInvestController.java
  src/main/java/com/prgrms/ijuju/domain/stock/adv/advancedinvest/dto/request/AdvancedInvestRequestDto.java
  src/main/java/com/prgrms/ijuju/domain/stock/adv/advancedinvest/dto/request/AdvancedRequestDTO.java
  src/main/java/com/prgrms/ijuju/domain/stock/adv/advancedinvest/dto/request/StockTransactionRequestDto.java
  src/main/java/com/prgrms/ijuju/domain/stock/adv/advancedinvest/dto/request/WebSocketRequestDto.java
  src/main/java/com/prgrms/ijuju/domain/stock/adv/advancedinvest/dto/response/AdvStockResponseDto.java
  src/main/java/com/prgrms/ijuju/domain/stock/adv/advancedinvest/dto/response/AdvancedInvestResponseDto.java
  src/main/java/com/prgrms/ijuju/domain/stock/adv/advancedinvest/dto/response/AdvancedResponseDTO.java
  src/main/java/com/prgrms/ijuju/domain/stock/adv/advancedinvest/entity/AdvancedInvest.java
  src/main/java/com/prgrms/ijuju/domain/stock/adv/advancedinvest/handler/AdvancedInvestWebSocketHandler.java
  src/main/java/com/prgrms/ijuju/domain/stock/adv/advancedinvest/repository/AdvancedInvestRepository.java
  src/main/java/com/prgrms/ijuju/domain/stock/adv/advancedinvest/service/AdvancedInvestService.java
  src/main/java/com/prgrms/ijuju/domain/stock/adv/advancedinvest/service/AdvancedInvestServiceImpl.java
  src/main/java/com/prgrms/ijuju/domain/stock/adv/advstock/repository/AdvStockRepository.java
  src/main/java/com/prgrms/ijuju/domain/stock/adv/stockrecord/constant/TradeType.java
  src/main/java/com/prgrms/ijuju/domain/stock/adv/stockrecord/controller/StockRecordController.java
  src/main/java/com/prgrms/ijuju/domain/stock/adv/stockrecord/dto/request/StockRecordRequestDto.java
  src/main/java/com/prgrms/ijuju/domain/stock/adv/stockrecord/dto/response/StockRecordResponseDto.java
  src/main/java/com/prgrms/ijuju/domain/stock/adv/stockrecord/entity/StockRecord.java
  src/main/java/com/prgrms/ijuju/domain/stock/adv/stockrecord/repository/StockRecordRepository.java
  src/main/java/com/prgrms/ijuju/domain/stock/adv/stockrecord/service/StockRecordService.java
  src/main/java/com/prgrms/ijuju/domain/stock/adv/stockrecord/service/StockRecordServiceImpl.java
  src/main/java/com/prgrms/ijuju/global/config/WebSocketConfig.java
Labels: ✨ Feature

#60 [Refactor] AdvInvest 오류 수정
  src/main/java/com/prgrms/ijuju/domain/stock/adv/advstock/controller/AdvStockController.java
  src/main/java/com/prgrms/ijuju/domain/stock/adv/stockrecord/controller/StockRecordController.java
  src/main/java/com/prgrms/ijuju/domain/stock/adv/stockrecord/service/StockRecordServiceImpl.java
Labels: 🔧 Refactor

#62 [Feat] 랭킹시스템 구현
  src/main/java/com/prgrms/ijuju/domain/member/entity/Member.java
  src/main/java/com/prgrms/ijuju/domain/member/repository/MemberRepository.java
  src/main/java/com/prgrms/ijuju/domain/point/repository/PointDetailsRepository.java
  src/main/java/com/prgrms/ijuju/domain/ranking/controller/RankingController.java
  src/main/java/com/prgrms/ijuju/domain/ranking/dto/response/RankingResponse.java
  src/main/java/com/prgrms/ijuju/domain/ranking/entity/Ranking.java
  src/main/java/com/prgrms/ijuju/domain/ranking/repository/RankingRepository.java
  src/main/java/com/prgrms/ijuju/domain/ranking/scheduler/WeeklyRankingScheduler.java
  src/main/java/com/prgrms/ijuju/domain/ranking/service/RankingService.java
  src/main/java/com/prgrms/ijuju/global/config/ObjectMapperConfig.java
  src/test/java/com/prgrms/ijuju/domain/ranking/controller/RankingControllerTest.java
  src/test/java/com/prgrms/ijuju/domain/ranking/controller/WithMockCustomUser.java
  src/test/java/com/prgrms/ijuju/domain/ranking/controller/WithMockCustomUserSecurityContextFactory.java
  src/test/java/com/prgrms/ijuju/domain/ranking/repository/RankingRepositoryTest.java
  src/test/java/com/prgrms/ijuju/domain/ranking/scheduler/WeeklyRankingSchedulerTest.java
  src/test/java/com/prgrms/ijuju/domain/ranking/service/RankingServiceTest.java
Labels: ✨ Feature

#67 [Refactor] 중급 주식 멤버아이디변경 및 예외처리
  src/main/java/com/prgrms/ijuju/domain/ranking/controller/RankingController.java
  src/main/java/com/prgrms/ijuju/domain/stock/mid/controller/MidStockController.java
  src/main/java/com/prgrms/ijuju/domain/stock/mid/dto/response/ErrorMidResponse.java
  src/main/java/com/prgrms/ijuju/domain/stock/mid/service/MidStockTradeService.java
  src/main/java/com/prgrms/ijuju/global/error/GlobalExceptionHandler.java
Labels: 🔧 Refactor

#69 [Feat] 아바타 엔티티 구현
  src/main/java/com/prgrms/ijuju/domain/avatar/controller/AdminItemController.java
  src/main/java/com/prgrms/ijuju/domain/avatar/controller/ItemController.java
  src/main/java/com/prgrms/ijuju/domain/avatar/dto/request/ItemRequestDTO.java
  src/main/java/com/prgrms/ijuju/domain/avatar/dto/response/ItemResponseDTO.java
  src/main/java/com/prgrms/ijuju/domain/avatar/entity/Avatar.java
  src/main/java/com/prgrms/ijuju/domain/avatar/entity/Inventory.java
  src/main/java/com/prgrms/ijuju/domain/avatar/entity/Item.java
  src/main/java/com/prgrms/ijuju/domain/avatar/entity/ItemCategory.java
  src/main/java/com/prgrms/ijuju/domain/avatar/entity/Purchase.java
  src/main/java/com/prgrms/ijuju/domain/avatar/exception/AvatarException.java
  src/main/java/com/prgrms/ijuju/domain/avatar/exception/ItemException.java
  src/main/java/com/prgrms/ijuju/domain/avatar/exception/ItemTaskException.java
  src/main/java/com/prgrms/ijuju/domain/avatar/repository/AvatarRepository.java
  src/main/java/com/prgrms/ijuju/domain/avatar/repository/ItemRepository.java
  src/main/java/com/prgrms/ijuju/domain/avatar/repository/PurchaseRepository.java
  src/main/java/com/prgrms/ijuju/domain/avatar/service/AdminItemService.java
  src/main/java/com/prgrms/ijuju/domain/avatar/service/AvatarService.java
  src/main/java/com/prgrms/ijuju/domain/avatar/service/ItemService.java
  src/main/java/com/prgrms/ijuju/domain/member/controller/MemberController.java
  src/main/java/com/prgrms/ijuju/domain/member/dto/request/MemberRequestDTO.java
  src/main/java/com/prgrms/ijuju/domain/member/dto/response/MemberResponseDTO.java
  src/main/java/com/prgrms/ijuju/domain/member/entity/Member.java
  src/main/java/com/prgrms/ijuju/domain/member/service/MemberService.java
  src/main/java/com/prgrms/ijuju/domain/stock/adv/advancedinvest/handler/AdvancedInvestWebSocketHandler.java
  src/main/java/com/prgrms/ijuju/domain/stock/adv/advancedinvest/service/AdvancedInvestServiceImpl.java
  src/main/java/com/prgrms/ijuju/global/config/WebConfig.java
  src/main/java/com/prgrms/ijuju/global/util/WebSocketUtil.java
Labels: ✨ Feature, 🐞 BugFix

#70 [Fix] avatar import문 수정
  src/main/java/com/prgrms/ijuju/domain/avatar/controller/ItemController.java
  src/main/java/com/prgrms/ijuju/domain/avatar/dto/request/ItemRequestDTO.java
  src/main/java/com/prgrms/ijuju/domain/avatar/entity/Item.java
  src/main/java/com/prgrms/ijuju/domain/avatar/entity/Purchase.java
  src/main/java/com/prgrms/ijuju/domain/avatar/exception/ItemException.java
  src/main/java/com/prgrms/ijuju/domain/avatar/repository/PurchaseRepository.java
  src/main/java/com/prgrms/ijuju/domain/avatar/service/AvatarService.java
  src/main/java/com/prgrms/ijuju/domain/avatar/service/ItemService.java
  src/main/java/com/prgrms/ijuju/domain/member/entity/Member.java
  src/main/java/com/prgrms/ijuju/domain/member/service/MemberService.java
Labels: 🐞 BugFix

#73 [Fix] member 로그인 수정
  src/main/java/com/prgrms/ijuju/domain/avatar/controller/ItemController.java
  src/main/java/com/prgrms/ijuju/domain/avatar/dto/request/ItemRequestDTO.java
  src/main/java/com/prgrms/ijuju/domain/avatar/dto/response/ItemResponseDTO.java
  src/main/java/com/prgrms/ijuju/domain/avatar/entity/Avatar.java
  src/main/java/com/prgrms/ijuju/domain/avatar/entity/Inventory.java
  src/main/java/com/prgrms/ijuju/domain/avatar/service/AvatarService.java
  src/main/java/com/prgrms/ijuju/domain/avatar/service/ItemService.java
  src/main/java/com/prgrms/ijuju/domain/member/controller/MemberController.java
  src/main/java/com/prgrms/ijuju/global/config/WebConfig.java
Labels: 🐞 BugFix
