Repository prgrms-web-devcourse-final-project/WEB1_2_Child-Learn_BE, pull requests merged in 2024-12, with the labels that each got.

#77 [Fix] member-CreatedAt 버그 픽스
  src/main/java/com/prgrms/ijuju/domain/avatar/entity/Item.java
  src/main/java/com/prgrms/ijuju/domain/member/dto/response/MemberResponseDTO.java
  src/main/java/com/prgrms/ijuju/domain/member/entity/Member.java
Labels: 🐞 BugFix

#78 [Feat] Chat 기능 구현
  .github/workflows/deploy.yml
  Dockerfile
  build.gradle
  src/main/java/com/prgrms/ijuju/domain/chat/controller/ChatController.java
  src/main/java/com/prgrms/ijuju/domain/chat/controller/ChatMessageController.java
  src/main/java/com/prgrms/ijuju/domain/chat/dto/request/ChatMessageRequestDTO.java
  src/main/java/com/prgrms/ijuju/domain/chat/dto/request/ChatReadRequestDTO.java
  src/main/java/com/prgrms/ijuju/domain/chat/dto/request/CreateChatRoomRequestDTO.java
  src/main/java/com/prgrms/ijuju/domain/chat/dto/response/ChatMessageResponseDTO.java
  src/main/java/com/prgrms/ijuju/domain/chat/dto/response/ChatReadResponseDTO.java
  src/main/java/com/prgrms/ijuju/domain/chat/dto/response/ChatRoomListResponseDTO.java
  src/main/java/com/prgrms/ijuju/domain/chat/dto/response/UnreadCountResponseDTO.java
  src/main/java/com/prgrms/ijuju/domain/chat/entity/Chat.java
  src/main/java/com/prgrms/ijuju/domain/chat/entity/ChatRoom.java
  src/main/java/com/prgrms/ijuju/domain/chat/exception/ChatException.java
  src/main/java/com/prgrms/ijuju/domain/chat/repository/ChatRepository.java
  src/main/java/com/prgrms/ijuju/domain/chat/repository/ChatRoomRepository.java
  src/main/java/com/prgrms/ijuju/domain/chat/service/ChatService.java
  src/main/java/com/prgrms/ijuju/domain/friend/service/FriendService.java
  src/main/java/com/prgrms/ijuju/domain/stock/mid/dto/response/MidStockTradeInfo.java
  src/main/java/com/prgrms/ijuju/domain/stock/mid/repository/MidStockTradeRepository.java
  src/main/java/com/prgrms/ijuju/global/common/BaseTimeEntity.java
  src/main/java/com/prgrms/ijuju/global/config/WebSocketConfig.java
Labels: ✨ Feature

#87 [Feat] OX 퀴즈 기능 구현
  src/main/java/com/prgrms/ijuju/domain/minigame/oxquiz/oxquizdata/config/OXQuizDataInitializer.java
  src/main/java/com/prgrms/ijuju/domain/minigame/oxquiz/oxquizdata/entity/OXQuizData.java
  src/main/java/com/prgrms/ijuju/domain/minigame/oxquiz/oxquizdata/repository/OXQuizDataRepository.java
  src/main/java/com/prgrms/ijuju/domain/minigame/oxquiz/oxquizprogression/constant/Priority.java
  src/main/java/com/prgrms/ijuju/domain/minigame/oxquiz/oxquizprogression/controller/OXQuizProgressionController.java
  src/main/java/com/prgrms/ijuju/domain/minigame/oxquiz/oxquizprogression/dto/request/QuizRequestDto.java
  src/main/java/com/prgrms/ijuju/domain/minigame/oxquiz/oxquizprogression/dto/response/QuizResponseDto.java
  src/main/java/com/prgrms/ijuju/domain/minigame/oxquiz/oxquizprogression/entity/OXQuizProgression.java
  src/main/java/com/prgrms/ijuju/domain/minigame/oxquiz/oxquizprogression/repository/OXQuizProgressionRepository.java
  src/main/java/com/prgrms/ijuju/domain/minigame/oxquiz/oxquizprogression/scheduler/OXQuizProgressionScheduler.java
  src/main/java/com/prgrms/ijuju/domain/minigame/oxquiz/oxquizprogression/service/OXQuizProgressionService.java
  src/main/java/com/prgrms/ijuju/domain/minigame/oxquiz/oxquizprogression/service/OXQuizProgressionServiceImpl.java
  src/main/java/com/prgrms/ijuju/global/config/ApiSecurityConfigTest.java
  src/main/resources/application.yml
  src/main/resources/minigame-data/ox-quiz.json
Labels: ✨ Feature

#91 [Refacor] Friend 친구 관련 기능 추가 및 예외 처리 코드 리팩토링
  build.gradle
  src/main/java/com/prgrms/ijuju/domain/chat/entity/Chat.java
  src/main/java/com/prgrms/ijuju/domain/chat/exception/ChatException.java
  src/main/java/com/prgrms/ijuju/domain/chat/service/ChatService.java
  src/main/java/com/prgrms/ijuju/domain/friend/dto/response/FriendResponseDTO.java
  src/main/java/com/prgrms/ijuju/domain/friend/entity/FriendRequest.java
  src/main/java/com/prgrms/ijuju/domain/friend/entity/FriendshipStatus.java
  src/main/java/com/prgrms/ijuju/domain/friend/exception/FriendException.java
  src/main/java/com/prgrms/ijuju/domain/friend/service/FriendService.java
  src/main/java/com/prgrms/ijuju/domain/member/controller/MemberController.java
  src/main/java/com/prgrms/ijuju/domain/member/dto/response/MemberResponseDTO.java
  src/main/java/com/prgrms/ijuju/domain/member/repository/MemberRepository.java
  src/main/java/com/prgrms/ijuju/domain/member/service/MemberService.java
  src/main/java/com/prgrms/ijuju/domain/stock/mid/service/MidStockTradeService.java
  src/main/java/com/prgrms/ijuju/domain/wallet/entity/Wallet.java
  src/main/java/com/prgrms/ijuju/domain/wallet/exception/WalletException.java
  src/main/java/com/prgrms/ijuju/domain/wallet/service/TransactionService.java
  src/main/java/com/prgrms/ijuju/domain/wallet/service/WalletService.java
  src/main/java/com/prgrms/ijuju/global/exception/CustomException.java
  src/main/java/com/prgrms/ijuju/global/exception/GlobalExceptionHandler.java
Labels: ✨ Feature, 🐞 BugFix, 🔧 Refactor

#95 [Fix] 중급 주식 데이터 서버측 생성 버그 픽스
  src/main/java/com/prgrms/ijuju/domain/stock/mid/config/InitMidDb.java
  src/main/java/com/prgrms/ijuju/domain/stock/mid/controller/MidStockController.java
  src/main/java/com/prgrms/ijuju/domain/stock/mid/repository/MidStockPriceRepositoryImpl.java
Labels: 🐞 BugFix

#99 Feat : OAuth2 구현 셋팅
  build.gradle
  src/main/java/com/prgrms/ijuju/domain/avatar/service/ItemService.java
  src/main/java/com/prgrms/ijuju/domain/member/controller/MemberController.java
  src/main/java/com/prgrms/ijuju/domain/member/dto/request/MemberRequestDTO.java
  src/main/java/com/prgrms/ijuju/domain/member/dto/response/MemberResponseDTO.java
  src/main/java/com/prgrms/ijuju/domain/member/entity/Member.java
  src/main/java/com/prgrms/ijuju/domain/member/entity/Role.java
  src/main/java/com/prgrms/ijuju/domain/member/exception/MemberException.java
  src/main/java/com/prgrms/ijuju/domain/member/oAuth2/CustomOAuth2User.java
  src/main/java/com/prgrms/ijuju/domain/member/oAuth2/CustomUserDetailsService.java
  src/main/java/com/prgrms/ijuju/domain/member/oAuth2/CustomUserPrincipal.java
  src/main/java/com/prgrms/ijuju/domain/member/oAuth2/GoogleResponse.java
  src/main/java/com/prgrms/ijuju/domain/member/oAuth2/KakaoResponse.java
  src/main/java/com/prgrms/ijuju/domain/member/oAuth2/OAuth2Response.java
  src/main/java/com/prgrms/ijuju/domain/member/service/MemberService.java
  src/main/java/com/prgrms/ijuju/domain/member/service/OAuth2Service.java
  src/main/java/com/prgrms/ijuju/global/config/ApiSecurityConfig.java
Labels: ✨ Feature, 🐞 BugFix

#101 [Refactor] 모의 투자 초급 리팩토링 및 공통 에러 처리
  build.gradle
  src/main/java/com/prgrms/ijuju/domain/stock/begin/config/CacheConfig.java
  src/main/java/com/prgrms/ijuju/domain/stock/begin/controller/BeginStockController.java
  src/main/java/com/prgrms/ijuju/domain/stock/begin/dto/response/BeginStockResponse.java
  src/main/java/com/prgrms/ijuju/domain/stock/begin/exception/BeginStockErrorCode.java
  src/main/java/com/prgrms/ijuju/domain/stock/begin/exception/BeginStockException.java
  src/main/java/com/prgrms/ijuju/domain/stock/begin/scheduler/BeginStockScheduler.java
  src/main/java/com/prgrms/ijuju/domain/stock/begin/service/BeginStockGptService.java
  src/main/java/com/prgrms/ijuju/domain/stock/begin/service/BeginStockPriceService.java
  src/main/java/com/prgrms/ijuju/domain/stock/begin/service/BeginStockService.java
  src/main/java/com/prgrms/ijuju/global/common/dto/CommonErrorResponse.java
  src/main/java/com/prgrms/ijuju/global/exception/BusinessException.java
  src/main/java/com/prgrms/ijuju/global/exception/ErrorCode.java
  src/main/java/com/prgrms/ijuju/global/exception/GlobalExceptionHandler.java
Labels: ✨ Feature, 🐞 BugFix, 🔧 Refactor

#109 [Refactor] 모의 투자 초급 오늘의 데이터 수동 생성 API 조건 변경
  src/main/java/com/prgrms/ijuju/domain/stock/begin/controller/BeginStockController.java
Labels: 🔧 Refactor

#110 [Feat] Exception 글로벌 처리
  src/main/java/com/prgrms/ijuju/domain/avatar/entity/Avatar.java
  src/main/java/com/prgrms/ijuju/domain/avatar/entity/Purchase.java
  src/main/java/com/prgrms/ijuju/domain/avatar/exception/AvatarErrorCode.java
  src/main/java/com/prgrms/ijuju/domain/avatar/exception/AvatarException.java
  src/main/java/com/prgrms/ijuju/domain/avatar/exception/ItemErrorCode.java
  src/main/java/com/prgrms/ijuju/domain/avatar/exception/ItemException.java
  src/main/java/com/prgrms/ijuju/domain/avatar/exception/ItemTaskException.java
  src/main/java/com/prgrms/ijuju/domain/avatar/service/AdminItemService.java
  src/main/java/com/prgrms/ijuju/domain/avatar/service/AvatarService.java
  src/main/java/com/prgrms/ijuju/domain/avatar/service/FileStorageService.java
  src/main/java/com/prgrms/ijuju/domain/avatar/service/ItemService.java
  src/main/java/com/prgrms/ijuju/domain/member/controller/MemberController.java
  src/main/java/com/prgrms/ijuju/domain/member/dto/response/MemberResponseDTO.java
  src/main/java/com/prgrms/ijuju/domain/member/entity/Member.java
  src/main/java/com/prgrms/ijuju/domain/member/exception/MemberErrorCode.java
  src/main/java/com/prgrms/ijuju/domain/member/exception/MemberException.java
  src/main/java/com/prgrms/ijuju/domain/member/exception/MemberTaskException.java
  src/main/java/com/prgrms/ijuju/domain/member/oAuth2/CustomUserDetailsService.java
  src/main/java/com/prgrms/ijuju/domain/member/service/MemberService.java
  src/main/java/com/prgrms/ijuju/domain/ranking/controller/RankingController.java
  src/main/java/com/prgrms/ijuju/domain/stock/begin/service/BeginStockService.java
  src/main/java/com/prgrms/ijuju/global/exception/CustomException.java
  src/main/java/com/prgrms/ijuju/global/exception/GlobalExceptionHandler.java
  src/main/java/com/prgrms/ijuju/global/util/JwtUtil.java
Labels: ✨ Feature, 🐞 BugFix

#112 [Refactor] Wallet, Friend, Chat 글로벌 예외 처리 적용
  src/main/java/com/prgrms/ijuju/domain/chat/entity/Chat.java
  src/main/java/com/prgrms/ijuju/domain/chat/exception/ChatErrorCode.java
  src/main/java/com/prgrms/ijuju/domain/chat/exception/ChatException.java
  src/main/java/com/prgrms/ijuju/domain/chat/service/ChatService.java
  src/main/java/com/prgrms/ijuju/domain/friend/entity/FriendRequest.java
  src/main/java/com/prgrms/ijuju/domain/friend/exception/FriendErrorCode.java
  src/main/java/com/prgrms/ijuju/domain/friend/exception/FriendException.java
  src/main/java/com/prgrms/ijuju/domain/friend/service/FriendService.java
  src/main/java/com/prgrms/ijuju/domain/member/service/MemberService.java
  src/main/java/com/prgrms/ijuju/domain/stock/mid/service/MidStockTradeService.java
  src/main/java/com/prgrms/ijuju/domain/wallet/entity/Wallet.java
  src/main/java/com/prgrms/ijuju/domain/wallet/exception/WalletErrorCode.java
  src/main/java/com/prgrms/ijuju/domain/wallet/exception/WalletException.java
  src/main/java/com/prgrms/ijuju/domain/wallet/service/TransactionService.java
  src/main/java/com/prgrms/ijuju/domain/wallet/service/WalletService.java
  src/main/java/com/prgrms/ijuju/global/common/dto/ErrorResponse.java
  src/main/java/com/prgrms/ijuju/global/exception/CustomException.java
  src/main/java/com/prgrms/ijuju/global/exception/GlobalExceptionHandler.java
Labels: 🔧 Refactor

#114 [Refactor] 낱말 게임 로직 개선 및 글로벌 예외 처리 적용
  src/main/java/com/prgrms/ijuju/domain/minigame/wordquiz/controller/WordQuizController.java
  src/main/java/com/prgrms/ijuju/domain/minigame/wordquiz/dto/response/ErrorWordQuizResponse.java
  src/main/java/com/prgrms/ijuju/domain/minigame/wordquiz/dto/response/WordQuizResponse.java
  src/main/java/com/prgrms/ijuju/domain/minigame/wordquiz/exception/WordQuizErrorCode.java
  src/main/java/com/prgrms/ijuju/domain/minigame/wordquiz/exception/WordQuizException.java
  src/main/java/com/prgrms/ijuju/domain/minigame/wordquiz/service/WordQuizService.java
  src/main/java/com/prgrms/ijuju/global/common/dto/ErrorResponse.java
  src/main/java/com/prgrms/ijuju/global/exception/GlobalExceptionHandler.java
Labels: 🔧 Refactor

#116 [Fix] 낱말 게임 readOnly 어노테이션 제거
  src/main/java/com/prgrms/ijuju/domain/minigame/wordquiz/service/WordQuizService.java
Labels: 🐞 BugFix

#118 [Fix] Wallet 게임 결과 처리 포인트 등록 에러
  src/main/java/com/prgrms/ijuju/domain/wallet/dto/request/GamePointRequestDTO.java
Labels: 🐞 BugFix

#119 [Fix] webSocket config url 변경
  src/main/java/com/prgrms/ijuju/global/config/WebSocketConfig.java
Labels: 🐞 BugFix

#122 [Fix] Interceptor Bearer 키워드 처리 로직 변경
  src/main/java/com/prgrms/ijuju/global/auth/JwtHandshakeInterceptor.java
Labels: 🐞 BugFix

#125 [Refactor] 선택된 퀴즈를 확인하기 위한 로깅 추가
  src/main/java/com/prgrms/ijuju/domain/stock/begin/service/BeginStockService.java
Labels: 🔧 Refactor

#130 [Feat] 알림 SSE 구현
  .gitignore
  src/main/java/com/prgrms/ijuju/domain/notification/controller/NotificationController.java
  src/main/java/com/prgrms/ijuju/domain/notification/controller/SseNotificationController.java
  src/main/java/com/prgrms/ijuju/domain/notification/dto/request/FriendNotificationRequest.java
  src/main/java/com/prgrms/ijuju/domain/notification/dto/request/MessageNotificationRequest.java
  src/main/java/com/prgrms/ijuju/domain/notification/dto/request/NotificationRequestDto.java
  src/main/java/com/prgrms/ijuju/domain/notification/dto/response/NotificationResponseDto.java
  src/main/java/com/prgrms/ijuju/domain/notification/dto/response/SseNotificationResponseDto.java
  src/main/java/com/prgrms/ijuju/domain/notification/entity/Notification.java
  src/main/java/com/prgrms/ijuju/domain/notification/entity/NotificationType.java
  src/main/java/com/prgrms/ijuju/domain/notification/repository/EmitterRepository.java
  src/main/java/com/prgrms/ijuju/domain/notification/repository/NotificationRepository.java
  src/main/java/com/prgrms/ijuju/domain/notification/service/NotificationService.java
  src/main/java/com/prgrms/ijuju/domain/notification/service/SseNotificationService.java
Labels: ✨ Feature

#128 [Refactor] Chat 메시지 기능 리팩토링
  build.gradle
  src/main/java/com/prgrms/ijuju/domain/chat/controller/ChatController.java
  src/main/java/com/prgrms/ijuju/domain/chat/controller/ChatMessageController.java
  src/main/java/com/prgrms/ijuju/domain/chat/dto/request/ChatMessageRequestDTO.java
  src/main/java/com/prgrms/ijuju/domain/chat/dto/request/ChatReadRequestDTO.java
  src/main/java/com/prgrms/ijuju/domain/chat/dto/request/ChatRoomRequestDTO.java
  src/main/java/com/prgrms/ijuju/domain/chat/dto/response/ChatMessageResponseDTO.java
  src/main/java/com/prgrms/ijuju/domain/chat/dto/response/ChatReadResponseDTO.java
  src/main/java/com/prgrms/ijuju/domain/chat/dto/response/ChatRoomListResponseDTO.java
  src/main/java/com/prgrms/ijuju/domain/chat/entity/Chat.java
  src/main/java/com/prgrms/ijuju/domain/chat/entity/ChatRoom.java
  src/main/java/com/prgrms/ijuju/domain/chat/exception/ChatTaskException.java
  src/main/java/com/prgrms/ijuju/domain/chat/handler/ChatWebSocketHandler.java
  src/main/java/com/prgrms/ijuju/domain/chat/repository/ChatMessageRepository.java
  src/main/java/com/prgrms/ijuju/domain/chat/repository/ChatRepository.java
  src/main/java/com/prgrms/ijuju/domain/chat/repository/ChatRoomRepository.java
  src/main/java/com/prgrms/ijuju/domain/chat/service/ChatService.java
  src/main/java/com/prgrms/ijuju/domain/chat/service/ChatSessionService.java
  src/main/java/com/prgrms/ijuju/domain/chat/validation/ValidImage.java
  src/main/java/com/prgrms/ijuju/domain/chat/validation/ValidImageValidator.java
  src/main/java/com/prgrms/ijuju/domain/friend/exception/FriendTaskException.java
  src/main/java/com/prgrms/ijuju/domain/wallet/dto/response/ResultResponseDTO.java
  src/main/java/com/prgrms/ijuju/domain/wallet/exception/WalletTaskException.java
  src/main/java/com/prgrms/ijuju/domain/wallet/handler/WalletWebSocketHandler.java
  src/main/java/com/prgrms/ijuju/global/common/dto/ApiResponse.java
  src/main/java/com/prgrms/ijuju/global/config/MongoConfig.java
  src/main/java/com/prgrms/ijuju/global/config/RedisConfig.java
  src/main/java/com/prgrms/ijuju/global/config/WebSocketConfig.java
  src/main/resources/application-dev.yml
  src/main/resources/application.yml
  src/test/java/com/prgrms/ijuju/domain/chat/ChatControllerTest.java
  src/test/java/com/prgrms/ijuju/domain/minigame/wordquiz/Service/WordQuizServiceTest.java
Labels: ✨ Feature, 🔧 Refactor

#137 [Refactor] 글로벌 예외 처리- 중급주식, 카드뒤집기, 참조삭제 해결, 랜덤카드 로직 변경
  src/main/java/com/prgrms/ijuju/domain/member/entity/Member.java
  src/main/java/com/prgrms/ijuju/domain/minigame/flipcard/dto/response/ErrorFlipCardResponse.java
  src/main/java/com/prgrms/ijuju/domain/minigame/flipcard/dto/response/PlayFlipCardAvailable.java
  src/main/java/com/prgrms/ijuju/domain/minigame/flipcard/entity/LimitCardGame.java
  src/main/java/com/prgrms/ijuju/domain/minigame/flipcard/exception/FlipCardErrorCode.java
  src/main/java/com/prgrms/ijuju/domain/minigame/flipcard/exception/FlipCardException.java
  src/main/java/com/prgrms/ijuju/domain/minigame/flipcard/repository/FlipCardRepository.java
  src/main/java/com/prgrms/ijuju/domain/minigame/flipcard/service/FlipCardService.java
  src/main/java/com/prgrms/ijuju/domain/ranking/dto/response/RankingResponse.java
  src/main/java/com/prgrms/ijuju/domain/ranking/entity/Ranking.java
  src/main/java/com/prgrms/ijuju/domain/stock/mid/controller/MidStockController.java
  src/main/java/com/prgrms/ijuju/domain/stock/mid/dto/request/MidStockTradePointRequest.java
  src/main/java/com/prgrms/ijuju/domain/stock/mid/dto/response/ErrorMidResponse.java
  src/main/java/com/prgrms/ijuju/domain/stock/mid/dto/response/MidStockPriceResponse.java
  src/main/java/com/prgrms/ijuju/domain/stock/mid/dto/response/MidStockTradeInfo.java
  src/main/java/com/prgrms/ijuju/domain/stock/mid/dto/response/TradeAvailableResponse.java
  src/main/java/com/prgrms/ijuju/domain/stock/mid/entity/MidStockPrice.java
  src/main/java/com/prgrms/ijuju/domain/stock/mid/entity/MidStockTrade.java
  src/main/java/com/prgrms/ijuju/domain/stock/mid/exception/MidStockErrorCode.java
  src/main/java/com/prgrms/ijuju/domain/stock/mid/exception/MidStockException.java
  src/main/java/com/prgrms/ijuju/domain/stock/mid/service/MidStockService.java
  src/main/java/com/prgrms/ijuju/domain/stock/mid/service/MidStockTradeService.java
  src/main/java/com/prgrms/ijuju/global/exception/GlobalExceptionHandler.java
Labels: 🔧 Refactor

#139 [Feat] 버그 픽스 및 OAuth2 서비스 수정
  build.gradle
  src/main/java/com/prgrms/ijuju/domain/avatar/controller/ItemController.java
  src/main/java/com/prgrms/ijuju/domain/avatar/dto/request/ItemRequestDTO.java
  src/main/java/com/prgrms/ijuju/domain/avatar/dto/response/ItemResponseDTO.java
  src/main/java/com/prgrms/ijuju/domain/avatar/entity/Avatar.java
  src/main/java/com/prgrms/ijuju/domain/avatar/service/AvatarService.java
  src/main/java/com/prgrms/ijuju/domain/avatar/service/ItemService.java
  src/main/java/com/prgrms/ijuju/domain/member/controller/MemberController.java
  src/main/java/com/prgrms/ijuju/domain/member/dto/request/MemberRequestDTO.java
  src/main/java/com/prgrms/ijuju/domain/member/entity/Member.java
  src/main/java/com/prgrms/ijuju/domain/member/exception/MemberErrorCode.java
  src/main/java/com/prgrms/ijuju/domain/member/oAuth2/CustomOAuth2User.java
  src/main/java/com/prgrms/ijuju/domain/member/oAuth2/GoogleResponse.java
  src/main/java/com/prgrms/ijuju/domain/member/oAuth2/KakaoResponse.java
  src/main/java/com/prgrms/ijuju/domain/member/oAuth2/OAuth2Response.java
  src/main/java/com/prgrms/ijuju/domain/member/service/MemberService.java
  src/main/java/com/prgrms/ijuju/domain/member/service/OAuth2Service.java
Labels: ✨ Feature, 🐞 BugFix

#141 [Fix] MongoDB URI 설정값 주입을 위한 value 적용
  src/main/java/com/prgrms/ijuju/global/config/MongoConfig.java
Labels: 🐞 BugFix

#142 [Refactor] 낱말 퀴즈 세션 관리 수정 및 로직 개선, 낱말 데이터 일부 변경
  src/main/java/com/prgrms/ijuju/domain/minigame/wordquiz/controller/WordQuizController.java
  src/main/java/com/prgrms/ijuju/domain/minigame/wordquiz/dto/response/WordQuizResponse.java
  src/main/java/com/prgrms/ijuju/domain/minigame/wordquiz/entity/LimitWordQuiz.java
  src/main/java/com/prgrms/ijuju/domain/minigame/wordquiz/service/WordQuizService.java
  src/main/resources/minigame-data/korean-words-game.json
Labels: 🐞 BugFix, 🔧 Refactor

#144 [Fix] 모의 투자 초급 스케줄링 기준 수정
  src/main/java/com/prgrms/ijuju/domain/stock/begin/service/BeginStockPriceService.java
Labels: 🐞 BugFix

#147 [Refactor] Chat 리팩토링
  src/main/java/com/prgrms/ijuju/domain/chat/aop/ChatLoggingAspect.java
  src/main/java/com/prgrms/ijuju/domain/chat/controller/ChatController.java
  src/main/java/com/prgrms/ijuju/domain/chat/controller/ChatMessageController.java
  src/main/java/com/prgrms/ijuju/domain/chat/entity/ChatRoom.java
  src/main/java/com/prgrms/ijuju/domain/chat/exception/ChatErrorCode.java
  src/main/java/com/prgrms/ijuju/domain/chat/exception/ChatTaskException.java
  src/main/java/com/prgrms/ijuju/domain/chat/handler/ChatWebSocketHandler.java
  src/main/java/com/prgrms/ijuju/domain/chat/repository/ChatMessageRepository.java
  src/main/java/com/prgrms/ijuju/domain/chat/service/ChatCacheService.java
  src/main/java/com/prgrms/ijuju/domain/chat/service/ChatService.java
  src/main/java/com/prgrms/ijuju/global/config/ApiSecurityConfig.java
  src/main/java/com/prgrms/ijuju/global/config/MongoConfig.java
  src/main/java/com/prgrms/ijuju/global/config/RedisCacheConfig.java
  src/main/java/com/prgrms/ijuju/global/config/WebSocketConfig.java
Labels: 🔧 Refactor

#151 [Feat] 알림 예외, 로그 처리
  src/main/java/com/prgrms/ijuju/domain/notification/controller/NotificationController.java
  src/main/java/com/prgrms/ijuju/domain/notification/controller/SseNotificationController.java
  src/main/java/com/prgrms/ijuju/domain/notification/exception/NotificationErrorCode.java
  src/main/java/com/prgrms/ijuju/domain/notification/exception/NotificationException.java
  src/main/java/com/prgrms/ijuju/domain/notification/service/NotificationService.java
  src/main/java/com/prgrms/ijuju/domain/notification/service/SseNotificationService.java
Labels: ✨ Feature

#154 [Feat] 아이템 목록 조회 구현
  src/main/java/com/prgrms/ijuju/domain/avatar/controller/ItemController.java
  src/main/java/com/prgrms/ijuju/domain/avatar/service/ItemService.java
Labels: ✨ Feature

#157 [Fix] sse 연결 설정 수정
  src/main/java/com/prgrms/ijuju/domain/notification/controller/SseNotificationController.java
  src/main/java/com/prgrms/ijuju/domain/notification/exception/NotificationErrorCode.java
  src/main/java/com/prgrms/ijuju/domain/notification/repository/EmitterRepository.java
  src/main/java/com/prgrms/ijuju/domain/notification/service/NotificationService.java
  src/main/java/com/prgrms/ijuju/domain/notification/service/SseNotificationService.java
Labels: 🐞 BugFix

#158 [Feat] Chat 엔드포인트에 Redis 연결 테스트 추가
  src/main/java/com/prgrms/ijuju/domain/chat/controller/ChatController.java
  src/main/java/com/prgrms/ijuju/domain/chat/scheduler/RedisHealthCheckScheduler.java
  src/main/java/com/prgrms/ijuju/domain/chat/service/ChatSessionService.java
  src/main/java/com/prgrms/ijuju/global/config/ApiSecurityConfig.java
  src/main/resources/application-dev.yml
Labels: ✨ Feature

#160 [Refactor] Member 회원검색 시 본인 제외로 수정
  src/main/java/com/prgrms/ijuju/domain/member/controller/MemberController.java
  src/main/java/com/prgrms/ijuju/domain/member/repository/MemberRepository.java
  src/main/java/com/prgrms/ijuju/domain/member/service/MemberService.java
  src/main/java/com/prgrms/ijuju/domain/stock/adv/advstock/service/AdvStockServiceImpl.java
Labels: 🔧 Refactor

#162 [Fix] AdvInvest Handler, 잘못된 요청 무시 구현
  src/main/java/com/prgrms/ijuju/domain/stock/adv/advancedinvest/handler/AdvancedInvestWebSocketHandler.java
Labels: 🐞 BugFix

#163 Fix: AdvStock 주말에 데이터 안날라오는 오류 수정
  src/main/java/com/prgrms/ijuju/domain/stock/adv/advstock/scheduler/AdvStockScheduler.java
  src/main/java/com/prgrms/ijuju/domain/stock/adv/advstock/util/DateUtil.java
Labels: 🐞 BugFix

#164 Refactor: sse 재연결 타임 1초에서 3초로 변경
  src/main/java/com/prgrms/ijuju/domain/notification/service/SseNotificationService.java
Labels: 🔧 Refactor

#165 Fix: sse 재연결시 의미있는 데이터 전송으로 변경
  src/main/java/com/prgrms/ijuju/domain/notification/service/SseNotificationService.java
Labels: 🔧 Refactor

#171 [Feat] infra 헬스체크 기능 구현
  src/main/java/com/prgrms/ijuju/domain/infra/controller/HealthCheckController.java
Labels: ✨ Feature, 🌏 Depoly

#173 [Feat] 헬스체크 시큐리티 인증 제외 추가
  src/main/java/com/prgrms/ijuju/global/config/ApiSecurityConfig.java
Labels: 🌏 Depoly

#181 [Refactor] 아이템 구매/장착/해제 시 반환 값 추가
  src/main/java/com/prgrms/ijuju/domain/avatar/dto/response/ItemResponseDTO.java
  src/main/java/com/prgrms/ijuju/domain/avatar/entity/Avatar.java
  src/main/java/com/prgrms/ijuju/domain/avatar/entity/Purchase.java
  src/main/java/com/prgrms/ijuju/domain/avatar/service/AvatarService.java
  src/main/java/com/prgrms/ijuju/domain/avatar/service/ItemService.java
  src/main/java/com/prgrms/ijuju/domain/member/controller/MemberController.java
  src/main/java/com/prgrms/ijuju/domain/member/dto/request/MemberRequestDTO.java
  src/main/java/com/prgrms/ijuju/domain/member/entity/Member.java
  src/main/java/com/prgrms/ijuju/domain/member/service/MemberService.java
Labels: 🔧 Refactor

#183 [Fix] AdvancedInvest 반복 재연결 오류 수정
  src/main/java/com/prgrms/ijuju/domain/stock/adv/advancedinvest/service/AdvancedInvestServiceImpl.java
Labels: 🐞 BugFix

#185 [Feat] OXQuiz 난이도별 하루 제한 구현
  src/main/java/com/prgrms/ijuju/domain/minigame/oxquiz/oxquizprogression/controller/OXQuizProgressionController.java
  src/main/java/com/prgrms/ijuju/domain/minigame/oxquiz/oxquizprogression/entity/OXQuizProgression.java
  src/main/java/com/prgrms/ijuju/domain/minigame/oxquiz/oxquizprogression/service/OXQuizProgressionService.java
Labels: ✨ Feature

#186 [Refactor] AdvInvest 타이머 시간 변경
  src/main/java/com/prgrms/ijuju/domain/stock/adv/advancedinvest/service/AdvancedInvestServiceImpl.java
Labels: 🔧 Refactor

#192 [Add] infra 헬스체크 로깅 추가
  src/main/java/com/prgrms/ijuju/domain/infra/controller/HealthCheckController.java
Labels: 🌏 Depoly, 🔧 Refactor
